# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(667, 468)
        self.username_lbl = QtWidgets.QLabel(Dialog)
        self.username_lbl.setGeometry(QtCore.QRect(30, 40, 71, 16))
        self.username_lbl.setObjectName("username_lbl")
        self.password_lbl = QtWidgets.QLabel(Dialog)
        self.password_lbl.setGeometry(QtCore.QRect(30, 70, 60, 16))
        self.password_lbl.setObjectName("password_lbl")
        self.institution_lbl = QtWidgets.QLabel(Dialog)
        self.institution_lbl.setGeometry(QtCore.QRect(30, 100, 60, 16))
        self.institution_lbl.setObjectName("institution_lbl")
        self.enter_completed_courses_lbl = QtWidgets.QLabel(Dialog)
        self.enter_completed_courses_lbl.setGeometry(QtCore.QRect(30, 170, 161, 16))
        self.enter_completed_courses_lbl.setObjectName("enter_completed_courses_lbl")
        self.username_line_edit = QtWidgets.QLineEdit(Dialog)
        self.username_line_edit.setGeometry(QtCore.QRect(120, 40, 113, 21))
        self.username_line_edit.setObjectName("username_line_edit")
        self.major_line_edit = QtWidgets.QLineEdit(Dialog)
        self.major_line_edit.setGeometry(QtCore.QRect(120, 130, 113, 21))
        self.major_line_edit.setObjectName("major_line_edit")
        self.institution_line_edit = QtWidgets.QLineEdit(Dialog)
        self.institution_line_edit.setGeometry(QtCore.QRect(120, 100, 113, 21))
        self.institution_line_edit.setObjectName("institution_line_edit")
        self.password_line_edit = QtWidgets.QLineEdit(Dialog)
        self.password_line_edit.setGeometry(QtCore.QRect(120, 70, 113, 21))
        self.password_line_edit.setObjectName("password_line_edit")
        self.major_lbl = QtWidgets.QLabel(Dialog)
        self.major_lbl.setGeometry(QtCore.QRect(30, 130, 41, 16))
        self.major_lbl.setObjectName("major_lbl")
        self.register_btn = QtWidgets.QPushButton(Dialog)
        self.register_btn.setGeometry(QtCore.QRect(240, 420, 113, 32))
        self.register_btn.setObjectName("register_btn")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 240, 131, 16))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 200, 331, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.completed_course_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.completed_course_lbl.setObjectName("completed_course_lbl")
        self.horizontalLayout.addWidget(self.completed_course_lbl)
        self.course_line_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.course_line_edit.setText("")
        self.course_line_edit.setObjectName("course_line_edit")
        self.horizontalLayout.addWidget(self.course_line_edit)
        self.add_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.courses_list_widget = QtWidgets.QListWidget(Dialog)
        self.courses_list_widget.setGeometry(QtCore.QRect(30, 270, 321, 131))
        self.courses_list_widget.setObjectName("courses_list_widget")
        item = QtWidgets.QListWidgetItem()
        self.courses_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.courses_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.courses_list_widget.addItem(item)
        self.remove_btn = QtWidgets.QPushButton(Dialog)
        self.remove_btn.setGeometry(QtCore.QRect(120, 420, 113, 32))
        self.remove_btn.setObjectName("remove_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.username_lbl.setText(_translate("Dialog", "Username"))
        self.password_lbl.setText(_translate("Dialog", "Password"))
        self.institution_lbl.setText(_translate("Dialog", "Institution"))
        self.enter_completed_courses_lbl.setText(_translate("Dialog", "Enter Completed Courses"))
        self.major_lbl.setText(_translate("Dialog", "Major"))
        self.register_btn.setText(_translate("Dialog", "Register"))
        self.label_2.setText(_translate("Dialog", "Completed Courses"))
        self.completed_course_lbl.setText(_translate("Dialog", "Completed Course"))
        self.add_btn.setText(_translate("Dialog", "Add"))
        __sortingEnabled = self.courses_list_widget.isSortingEnabled()
        self.courses_list_widget.setSortingEnabled(False)
        item = self.courses_list_widget.item(0)
        item.setText(_translate("Dialog", "jjjj"))
        item = self.courses_list_widget.item(1)
        item.setText(_translate("Dialog", "kkkk"))
        item = self.courses_list_widget.item(2)
        item.setText(_translate("Dialog", "hklj;"))
        self.courses_list_widget.setSortingEnabled(__sortingEnabled)
        self.remove_btn.setText(_translate("Dialog", "Remove"))

